"""Integration tests for PDF export endpoint."""

import pytest
from sqlalchemy.orm import Session
from sqlalchemy.pool import StaticPool
from sqlalchemy import create_engine
from io import BytesIO
import pdfplumber

from app.models.user import User
from app.models.ai_system import AISystem, RiskLevel, ComplianceStatus
from app.models.document import Document, DocumentType, DocumentStatus
from app.core.security import create_access_token


@pytest.fixture
def test_user(client, db_session):
    user = User(
        email="test@example.com",
        hashed_password="$2b$12$R9h31cIPz0yO8W4gw2love.a4UtcWLU7pHPti3/T.D18SMsKvRHO2",
        is_active=True,
        company_name="Test Company"
    )
    db_session.add(user)
    db_session.commit()
    db_session.refresh(user)
    return user


@pytest.fixture
def test_ai_system(db_session, test_user):
    ai_system = AISystem(
        owner_id=test_user.id,
        name="Test AI System",
        description="Test AI system for compliance",
        version="1.0.0",
        use_case="Testing",
        sector="Technology",
        risk_level=RiskLevel.HIGH,
        compliance_status=ComplianceStatus.IN_PROGRESS,
        compliance_score=50
    )
    db_session.add(ai_system)
    db_session.commit()
    db_session.refresh(ai_system)
    return ai_system


@pytest.fixture
def test_document(db_session, test_user, test_ai_system):
    document = Document(
        owner_id=test_user.id,
        ai_system_id=test_ai_system.id,
        title="Technical Documentation - Test AI System",
        document_type=DocumentType.TECHNICAL_DOCUMENTATION,
        status=DocumentStatus.GENERATED,
        content="""# Technical Documentation - Test AI System

## 1. General Description
**System Name:** Test AI System
**Version:** 1.0.0
**Use Case:** Testing
**Sector:** Technology

## 2. Intended Purpose
This is a test system for compliance documentation purposes.

## 3. System Architecture
The system consists of the following components:
- API Layer
- Database Layer
- ML Model Layer
- Monitoring Layer

## 4. Training Data
- Data sources: Test datasets
- Data preprocessing steps: Normalization and validation
- Data quality measures: 99% accuracy

## 5. Model Information
- Algorithm/model type: Test neural network
- Training methodology: Supervised learning
- Performance metrics: F1 score 0.95

## 6. Input/Output Specifications
- Expected inputs: JSON objects with features
- Output format: Predictions with confidence scores

## 7. Limitations and Risks
- Known limitations: Test model only
- Identified risks: None in test environment

## 8. Human Oversight Measures
- Human-in-the-loop mechanisms: Manual review required
- Override capabilities: Available in admin panel

## 9. Logging and Monitoring
- What is logged: All predictions and inputs
- Monitoring procedures: Real-time dashboards

---
Generated by EU AI Act Compliance Tool
"""
    )
    db_session.add(document)
    db_session.commit()
    db_session.refresh(document)
    return document


@pytest.fixture
def auth_headers(test_user):
    token = create_access_token(data={"sub": str(test_user.id)})
    return {"Authorization": f"Bearer {token}"}


class TestPDFExportEndpoint:

    def test_pdf_export_returns_200_status(self, client, auth_headers, test_document):
        response = client.get(
            f"/api/v1/documents/{test_document.id}/pdf",
            headers=auth_headers
        )
        assert response.status_code == 200

    def test_pdf_export_returns_pdf_content_type(self, client, auth_headers, test_document):
        response = client.get(
            f"/api/v1/documents/{test_document.id}/pdf",
            headers=auth_headers
        )
        assert response.headers["content-type"] == "application/pdf"

    def test_pdf_export_response_starts_with_pdf_magic_bytes(self, client, auth_headers, test_document):
        response = client.get(
            f"/api/v1/documents/{test_document.id}/pdf",
            headers=auth_headers
        )
        assert response.content.startswith(b"%PDF-"), "PDF does not start with magic bytes"

    def test_pdf_export_response_larger_than_1kb(self, client, auth_headers, test_document):
        response = client.get(
            f"/api/v1/documents/{test_document.id}/pdf",
            headers=auth_headers
        )
        assert len(response.content) > 1024

    def test_pdf_export_document_not_found(self, client, auth_headers):
        response = client.get("/api/v1/documents/99999/pdf", headers=auth_headers)
        assert response.status_code == 404

    def test_pdf_export_unauthorized_access(self, client, test_document):
        """Test that 401/403 is returned without authentication."""
        # Remove global auth mock so real auth enforcement runs
        from app.core.security import get_current_user
        from app.main import app
        app.dependency_overrides.pop(get_current_user, None)

        response = client.get(f"/api/v1/documents/{test_document.id}/pdf")
        assert response.status_code in [401, 403]

    def test_pdf_export_includes_document_title(self, client, auth_headers, test_document):
        response = client.get(
            f"/api/v1/documents/{test_document.id}/pdf",
            headers=auth_headers
        )
        pdf_file = BytesIO(response.content)
        with pdfplumber.open(pdf_file) as pdf:
            first_page_text = pdf.pages[0].extract_text()
            assert test_document.title in first_page_text

    def test_pdf_export_has_filename(self, client, auth_headers, test_document):
        response = client.get(
            f"/api/v1/documents/{test_document.id}/pdf",
            headers=auth_headers
        )
        content_disposition = response.headers.get("content-disposition", "")
        assert "filename" in content_disposition or test_document.title in content_disposition

    def test_pdf_export_escapes_user_controlled_markup(
        self, client, auth_headers, test_user, test_ai_system, db_session
    ):
        document = Document(
            owner_id=test_user.id,
            ai_system_id=test_ai_system.id,
            title='Markup <b>Title</b> "draft"',
            document_type=DocumentType.TECHNICAL_DOCUMENTATION,
            status=DocumentStatus.GENERATED,
            content=(
                "# <b>Injected heading</b>\n"
                "Plain text with <font color=\"red\">unterminated markup\n"
                "- <i>Injected bullet</i>\n"
                "**Bold <script>alert(1)</script> text**"
            ),
        )
        db_session.add(document)
        db_session.commit()

        response = client.get(
            f"/api/v1/documents/{document.id}/pdf",
            headers=auth_headers,
        )

        assert response.status_code == 200
        assert response.content.startswith(b"%PDF-")

        pdf_file = BytesIO(response.content)
        with pdfplumber.open(pdf_file) as pdf:
            first_page_text = pdf.pages[0].extract_text()
            assert "Injected heading" in first_page_text
            assert "unterminated markup" in first_page_text
            assert "alert(1)" in first_page_text

    def test_pdf_export_sanitizes_download_filename(
        self, client, auth_headers, test_user, test_ai_system, db_session
    ):
        document = Document(
            owner_id=test_user.id,
            ai_system_id=test_ai_system.id,
            title='Unsafe "Q4"/Report\nFinal',
            document_type=DocumentType.TECHNICAL_DOCUMENTATION,
            status=DocumentStatus.GENERATED,
            content="# Safe content\n\nThis document should export.",
        )
        db_session.add(document)
        db_session.commit()

        response = client.get(
            f"/api/v1/documents/{document.id}/pdf",
            headers=auth_headers,
        )

        assert response.status_code == 200
        content_disposition = response.headers["content-disposition"]
        assert "\n" not in content_disposition
        assert 'filename="Unsafe _Q4_ReportFinal.pdf"' in content_disposition
        assert "filename*=UTF-8''Unsafe%20_Q4_ReportFinal.pdf" in content_disposition

    def test_pdf_export_multiple_documents(self, client, auth_headers, test_user, test_ai_system, db_session):
        doc1 = Document(
            owner_id=test_user.id,
            ai_system_id=test_ai_system.id,
            title="Risk Assessment - Test",
            document_type=DocumentType.RISK_ASSESSMENT,
            status=DocumentStatus.GENERATED,
            content="# Risk Assessment\n\nThis is a risk assessment document."
        )
        doc2 = Document(
            owner_id=test_user.id,
            ai_system_id=test_ai_system.id,
            title="Conformity Declaration - Test",
            document_type=DocumentType.CONFORMITY_DECLARATION,
            status=DocumentStatus.GENERATED,
            content="# Declaration of Conformity\n\nWe hereby declare conformity."
        )
        db_session.add(doc1)
        db_session.add(doc2)
        db_session.commit()

        response1 = client.get(f"/api/v1/documents/{doc1.id}/pdf", headers=auth_headers)
        response2 = client.get(f"/api/v1/documents/{doc2.id}/pdf", headers=auth_headers)

        assert response1.status_code == 200
        assert response2.status_code == 200
        assert response1.content.startswith(b"%PDF-")
        assert response2.content.startswith(b"%PDF-")
        assert len(response1.content) > 1024
        assert len(response2.content) > 1024

    def test_pdf_export_empty_content_error(self, client, auth_headers, test_user, test_ai_system, db_session):
        empty_doc = Document(
            owner_id=test_user.id,
            ai_system_id=test_ai_system.id,
            title="Empty Document",
            document_type=DocumentType.TECHNICAL_DOCUMENTATION,
            status=DocumentStatus.DRAFT,
            content=""
        )
        db_session.add(empty_doc)
        db_session.commit()

        response = client.get(
            f"/api/v1/documents/{empty_doc.id}/pdf",
            headers=auth_headers
        )
        assert response.status_code == 400

    def test_pdf_export_cross_user_security(self, client, test_user, test_ai_system, test_document, db_session):
        """Test that users cannot access other users' documents."""
        # Remove global auth mock so real JWT validation runs
        from app.core.security import get_current_user
        from app.main import app
        app.dependency_overrides.pop(get_current_user, None)

        other_user = User(
            email="other@example.com",
            hashed_password="$2b$12$R9h31cIPz0yO8W4gw2love.a4UtcWLU7pHPti3/T.D18SMsKvRHO2",
            is_active=True
        )
        db_session.add(other_user)
        db_session.commit()

        other_token = create_access_token(data={"sub": str(other_user.id)})
        other_headers = {"Authorization": f"Bearer {other_token}"}

        response = client.get(
            f"/api/v1/documents/{test_document.id}/pdf",
            headers=other_headers
        )
        assert response.status_code == 404, "Should not be able to access other user's document"
